const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM(fs.readFileSync(__dirname+'/index.html','utf8'),{runScripts:'outside-only'}).window;
let created=0,privateOpened=0,authHandler;
w.getCurrentTeacher=()=>({uid:'test',name:'יהודית'});w.showCreateClub=()=>created++;
w.BookiPrivateLibrary={open:()=>privateOpened++};w.onTeacherAuthChange=cb=>{authHandler=cb};
w.setNavVisible=()=>{};w.showScreen=id=>{w.document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id===id))};
w.getAllStories=()=>[];w.BOOKI_LIBRARY_SHELVES=[];
w.eval(fs.readFileSync(__dirname+'/teacher-workspace.js','utf8'));
w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
const doc=w.document,home=doc.querySelector('#screen-teacher-dashboard'),list=doc.querySelector('#td-clubs-list'),libraries=doc.querySelector('#tw-dashboard-actions');
assert(home.classList.contains('tw-home'));assert.equal(home.querySelector('h2').textContent,'היי, יהודית');
assert(list.compareDocumentPosition(libraries)&w.Node.DOCUMENT_POSITION_FOLLOWING);
home.querySelector('.tw-new-club').click();assert.equal(created,1);
const personal=home.querySelector('.tw-library-personal');assert(personal);personal.click();assert.equal(privateOpened,1);
assert(home.querySelector('footer .btn-share-app')||home.querySelector('.header-actions .btn-share-app'));assert(home.querySelector('footer .btn-logout')||home.querySelector('.header-actions .btn-logout'));
assert.equal(home.querySelectorAll('.tw-library-link').length,3);
assert.equal(home.querySelectorAll('.tw-dashboard-action').length,0);
const firstLibrary=home.querySelector('.tw-library-link');assert(firstLibrary);firstLibrary.click();assert(doc.querySelector('#screen-teacher-booki-library').classList.contains('active'));
assert(doc.querySelector('#screen-teacher-booki-library').textContent.includes('סיפורים'));
assert(!home.textContent.includes('מתחילות כאן'));
const brandCount=()=>home.querySelectorAll('.tw-brand-label').length;
assert.equal(brandCount(),1);
// Simulate dashboard re-entry/rebuild; brand must remain singular.
w.showTeacherDashboard?.();w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
assert.equal(brandCount(),1);
console.log('PASS teacher home hierarchy, greeting, club creation, three libraries, footer actions, navigation and no duplicate brand on re-entry');
